### ISSUE TITLE
Syntax Error on Windows for valid HAR files

### ISSUE THREAD

**Issue by vworld** [deviantintegral/har#18]
Hi
Came across your repository when dealing with the syntax error in json_decode. It looks very awesome but it still gave me the syntac error.
You may want to implement the solution mentioned here -> https://stackoverflow.com/a/20845642

This solved my problem.

**Comment by deviantintegral** [comment]
Can you share a copy of the HAR that is causing the syntax error? Then I can add it as a test case.

**Comment by vworld** [comment]
Hi
Here is a file that I generated today.
The codes are:
`$fileLocation = __DIR__ . $harFileName;
        if (!file_exists($fileLocation)) {
            throw new harFileNotFound('Invalid File Location: ' . $fileLocation);
        }
        $harFileContent = file_get_contents($fileLocation);
        $this->harEntriesArray = json_decode($harStr, true)['log']['entries'];
        if (!$this->harEntriesArray) {
            throw new harFileInvalidFormat('Invalid JSON Format in HAR file: ' . $fileLocation);
        }`


[sample.zip](https://github.com/deviantintegral/har/files/5446900/sample.zip)

**Comment by deviantintegral** [comment]
Thanks for providing that sample. It's showing up as invalid for me on macOS too. Looking at the file with `xxd`:

```
$ xxd sample.har | head
00000000: efbb bf7b 226c 6f67 223a 7b22 7061 6765  ...{"log":{"page
00000010: 7322 3a5b 5d2c 2022 636f 6d6d 656e 7422  s":[], "comment"
```

It looks like there are three additional characters before the open brace (which is `7b`). I think the file is corrupt, or not a normal text file. Can you clarify how it's been generated? In contrast, note how an existing test case starts immediately with the `{` character:

```
$ xxd tests/fixtures/www.softwareishard.com-single-entry.har | head
00000000: 7b0a 2020 226c 6f67 223a 207b 0a20 2020  {.  "log": {.
00000010: 2022 7665 7273 696f 6e22 3a20 2231 2e32   "version": "1.2
```

**Comment by vworld** [comment]
Hi
The file is created with Fiddler -> File >> Expert >> HTTP Archive 1.2.
What I did to solve the problem was pass the file string read with `file_get_content` through the function below. Explanation in the commented links in the function.

private function cleanJSONString($jsonString) {
        // From -> https://stackoverflow.com/a/20845642
        // This will remove unwanted characters.
        // Check http://www.php.net/chr for details
        for ($i = 0; $i <= 31; ++$i) {
            $jsonString = str_replace(chr($i), "", $jsonString);
        }
        $jsonString = str_replace(chr(127), "", $jsonString);

        // This is the most common part
        // Some file begins with 'efbbbf' to mark the beginning of the file. (binary level)
        // here we detect it and we remove it, basically it's the first 3 characters 
        if (0 === strpos(bin2hex($jsonString), 'efbbbf')) {
            $jsonString = substr($jsonString, 3);
        }
        return $jsonString;
    }
