### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by mcorossigo** [deviantintegral/har#22]
Hello @deviantintegral 
Trying to install your nice package in a project running PHP8, and composer refuses quitting with:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - deviantintegral/har[0.1.0, ..., 0.1.2] require php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
    - Root composer.json requires deviantintegral/har * -> satisfiable by deviantintegral/har[0.1.0, 0.1.1, 0.1.2].
```

Composer version. 

A quick search found this: https://stackoverflow.com/questions/65454412/root-composer-json-requires-php-7-3-but-your-php-version-8-0-0-does-not-satis

Can you update the requirement to support PHP 8, assuming that there is no technical issues with it.
Thank you.

**Comment by deviantintegral** [comment]
Done! Glad you're finding this useful. I had two dependent libraries above that also needed updating. I think everything is good as tests all passed. `0.2.0` is building now. Let me know if you discover any unxpected bugs.

**Comment by deviantintegral** [comment]
Actually, I'm going to change the build job for the PHAR to use PHP 8 instead of 7.

**Comment by mcorossigo** [comment]
Thank you very much for the quick update. In the meantime I was using it with `composer update --ignore-platform-reqs`.
I'll update ASAP.
